# This is a basic workflow to help you get started with Actions

#Franco Vigil
#Diseñar realizar pedidos
#Validar Datos
#Generar e implementar clases necesarias
#Sebastian C.
#Validar datos 
#Ernie B.
#Generar e implemntar clases necesarias
